# Generated by Django 5.2.17 on 2026-09-17 04:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shop.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=200, verbose_name='name (BN)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='name (AR)')),
                ('code', models.SlugField(help_text='e.g. stationery', unique=True, verbose_name='code')),
                ('emoji', models.CharField(blank=True, default='📦', max_length=10, verbose_name='emoji')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name_bn'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='min subtotal')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='charge')),
                ('min_order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='min order')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('mobile', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{7,20}$', 'Enter a valid mobile number.')], verbose_name='mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('preferred_language', models.CharField(choices=[('bn', 'বাংলা'), ('en', 'English'), ('ar', 'العربية')], default='bn', max_length=5, verbose_name='preferred language')),
                ('country_code', models.CharField(blank=True, help_text='ISO2, e.g. BD', max_length=2, verbose_name='country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mobile'], name='shop_custom_mobile_bb8552_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='order no')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='placed', max_length=20, verbose_name='status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='delivery fee')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='discount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='total')),
                ('payment_method', models.CharField(choices=[('cod', 'COD'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card')], default='cod', max_length=20, verbose_name='payment method')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', max_length=20, verbose_name='payment status')),
                ('coupon_code', models.CharField(blank=True, max_length=30, verbose_name='coupon')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ordered at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customer')),
            ],
            options={
                'ordering': ['-ordered_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shop.order')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=200, verbose_name='name (BN)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='name (AR)')),
                ('sku', models.SlugField(help_text='unique, e.g. rivin-0001', unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='price')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='compare-at price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='MRP')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock')),
                ('emoji', models.CharField(blank=True, default='🛍️', max_length=10, verbose_name='emoji')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', validators=[shop.models.validate_product_image], verbose_name='image')),
                ('link', models.URLField(blank=True, verbose_name='external link')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='bestseller')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='category')),
            ],
            options={
                'ordering': ['sort_order', 'name_bn'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.JSONField(default=dict, help_text='{"bn": "...", "en": "...", "ar": "..."}', verbose_name='name snapshot')),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='unit price snapshot')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='qty')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='line total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('emoji', models.CharField(blank=True, default='⭐', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='default delivery charge')),
                ('min_order', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='min order')),
                ('theme', models.CharField(default='light', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bestsellers', models.ManyToManyField(blank=True, related_name='bestseller_in', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='positive = in, negative = out', verbose_name='delta')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='reason')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='shop.product')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
